<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookingSeeder extends Seeder
{
    public function run()
    {
        DB::table('bookings')->insert([
            [
                'guest_id' => 1,
                'room_id' => 1,
                'service_id' => 1,
                'check_in' => '2025-01-05',
                'check_out' => '2025-01-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 1,
                'room_id' => 1,
                'service_id' => 1,
                'check_in' => '2025-01-07',
                'check_out' => '2025-01-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 2,
                'room_id' => 2,
                'service_id' => null,
                'check_in' => '2025-02-08',
                'check_out' => '2025-02-11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 2,
                'room_id' => 2,
                'service_id' => null,
                'check_in' => '2025-02-08',
                'check_out' => '2025-02-11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 2,
                'room_id' => 2,
                'service_id' => null,
                'check_in' => '2025-02-08',
                'check_out' => '2025-02-11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 2,
                'room_id' => 2,
                'service_id' => null,
                'check_in' => '2025-02-08',
                'check_out' => '2025-02-11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 2,
                'room_id' => 2,
                'service_id' => null,
                'check_in' => '2025-02-08',
                'check_out' => '2025-02-11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 3,
                'room_id' => 3,
                'service_id' => 2,
                'check_in' => '2025-03-12',
                'check_out' => '2025-03-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 3,
                'room_id' => 3,
                'service_id' => 2,
                'check_in' => '2025-03-12',
                'check_out' => '2025-03-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 3,
                'room_id' => 3,
                'service_id' => 2,
                'check_in' => '2025-03-12',
                'check_out' => '2025-03-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 3,
                'room_id' => 3,
                'service_id' => 2,
                'check_in' => '2025-03-12',
                'check_out' => '2025-03-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 4,
                'room_id' => 4,
                'service_id' => 3,
                'check_in' => '2025-04-03',
                'check_out' => '2025-04-06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 4,
                'room_id' => 4,
                'service_id' => 3,
                'check_in' => '2025-04-03',
                'check_out' => '2025-04-06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 4,
                'room_id' => 4,
                'service_id' => 3,
                'check_in' => '2025-04-03',
                'check_out' => '2025-04-06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 4,
                'room_id' => 4,
                'service_id' => 3,
                'check_in' => '2025-04-03',
                'check_out' => '2025-04-06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 4,
                'room_id' => 4,
                'service_id' => 3,
                'check_in' => '2025-04-03',
                'check_out' => '2025-04-06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 4,
                'room_id' => 4,
                'service_id' => 3,
                'check_in' => '2025-04-03',
                'check_out' => '2025-04-06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 4,
                'room_id' => 4,
                'service_id' => 3,
                'check_in' => '2025-04-03',
                'check_out' => '2025-04-06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 4,
                'room_id' => 4,
                'service_id' => 3,
                'check_in' => '2025-04-03',
                'check_out' => '2025-04-06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 5,
                'room_id' => 5,
                'service_id' => 1,
                'check_in' => '2025-05-15',
                'check_out' => '2025-05-18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 5,
                'room_id' => 5,
                'service_id' => 1,
                'check_in' => '2025-05-15',
                'check_out' => '2025-05-18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 5,
                'room_id' => 5,
                'service_id' => 1,
                'check_in' => '2025-05-15',
                'check_out' => '2025-05-18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 5,
                'room_id' => 5,
                'service_id' => 1,
                'check_in' => '2025-05-15',
                'check_out' => '2025-05-18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 5,
                'room_id' => 5,
                'service_id' => 1,
                'check_in' => '2025-05-15',
                'check_out' => '2025-05-18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 5,
                'room_id' => 5,
                'service_id' => 1,
                'check_in' => '2025-05-15',
                'check_out' => '2025-05-18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 6,
                'room_id' => 1,
                'service_id' => null,
                'check_in' => '2025-06-01',
                'check_out' => '2025-06-04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 6,
                'room_id' => 1,
                'service_id' => null,
                'check_in' => '2025-06-01',
                'check_out' => '2025-06-04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 6,
                'room_id' => 1,
                'service_id' => null,
                'check_in' => '2025-06-01',
                'check_out' => '2025-06-04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 6,
                'room_id' => 1,
                'service_id' => null,
                'check_in' => '2025-06-01',
                'check_out' => '2025-06-04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 6,
                'room_id' => 1,
                'service_id' => null,
                'check_in' => '2025-06-01',
                'check_out' => '2025-06-04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 6,
                'room_id' => 1,
                'service_id' => null,
                'check_in' => '2025-06-01',
                'check_out' => '2025-06-04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 6,
                'room_id' => 1,
                'service_id' => null,
                'check_in' => '2025-06-01',
                'check_out' => '2025-06-04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 6,
                'room_id' => 1,
                'service_id' => null,
                'check_in' => '2025-06-01',
                'check_out' => '2025-06-04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 7,
                'room_id' => 2,
                'service_id' => 2,
                'check_in' => '2025-07-09',
                'check_out' => '2025-07-12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 7,
                'room_id' => 2,
                'service_id' => 2,
                'check_in' => '2025-07-09',
                'check_out' => '2025-07-12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 7,
                'room_id' => 2,
                'service_id' => 2,
                'check_in' => '2025-07-09',
                'check_out' => '2025-07-12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 7,
                'room_id' => 2,
                'service_id' => 2,
                'check_in' => '2025-07-09',
                'check_out' => '2025-07-12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 7,
                'room_id' => 2,
                'service_id' => 2,
                'check_in' => '2025-07-09',
                'check_out' => '2025-07-12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 7,
                'room_id' => 2,
                'service_id' => 2,
                'check_in' => '2025-07-09',
                'check_out' => '2025-07-12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 7,
                'room_id' => 2,
                'service_id' => 2,
                'check_in' => '2025-07-09',
                'check_out' => '2025-07-12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 8,
                'room_id' => 3,
                'service_id' => null,
                'check_in' => '2025-08-20',
                'check_out' => '2025-08-23',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 8,
                'room_id' => 3,
                'service_id' => null,
                'check_in' => '2025-08-20',
                'check_out' => '2025-08-23',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 8,
                'room_id' => 3,
                'service_id' => null,
                'check_in' => '2025-08-20',
                'check_out' => '2025-08-23',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 8,
                'room_id' => 3,
                'service_id' => null,
                'check_in' => '2025-08-20',
                'check_out' => '2025-08-23',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 8,
                'room_id' => 3,
                'service_id' => null,
                'check_in' => '2025-08-20',
                'check_out' => '2025-08-23',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 8,
                'room_id' => 3,
                'service_id' => null,
                'check_in' => '2025-08-20',
                'check_out' => '2025-08-23',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 9,
                'room_id' => 4,
                'service_id' => 3,
                'check_in' => '2025-09-05',
                'check_out' => '2025-09-09',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 9,
                'room_id' => 4,
                'service_id' => 3,
                'check_in' => '2025-09-05',
                'check_out' => '2025-09-09',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 9,
                'room_id' => 4,
                'service_id' => 3,
                'check_in' => '2025-09-05',
                'check_out' => '2025-09-09',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 9,
                'room_id' => 4,
                'service_id' => 3,
                'check_in' => '2025-09-05',
                'check_out' => '2025-09-09',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 9,
                'room_id' => 4,
                'service_id' => 3,
                'check_in' => '2025-09-05',
                'check_out' => '2025-09-09',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'guest_id' => 10,
                'room_id' => 5,
                'service_id' => 1,
                'check_in' => '2025-10-14',
                'check_out' => '2025-10-17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 10,
                'room_id' => 5,
                'service_id' => 1,
                'check_in' => '2025-10-14',
                'check_out' => '2025-10-17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 10,
                'room_id' => 5,
                'service_id' => 1,
                'check_in' => '2025-10-14',
                'check_out' => '2025-10-17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 10,
                'room_id' => 5,
                'service_id' => 1,
                'check_in' => '2025-10-14',
                'check_out' => '2025-10-17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 10,
                'room_id' => 5,
                'service_id' => 1,
                'check_in' => '2025-10-14',
                'check_out' => '2025-10-17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 10,
                'room_id' => 5,
                'service_id' => 1,
                'check_in' => '2025-10-14',
                'check_out' => '2025-10-17',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'guest_id' => 1,
                'room_id' => 1,
                'service_id' => 2,
                'check_in' => '2025-11-02',
                'check_out' => '2025-11-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 1,
                'room_id' => 1,
                'service_id' => 2,
                'check_in' => '2025-11-02',
                'check_out' => '2025-11-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 1,
                'room_id' => 1,
                'service_id' => 2,
                'check_in' => '2025-11-02',
                'check_out' => '2025-11-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 1,
                'room_id' => 1,
                'service_id' => 2,
                'check_in' => '2025-11-02',
                'check_out' => '2025-11-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 1,
                'room_id' => 1,
                'service_id' => 2,
                'check_in' => '2025-11-02',
                'check_out' => '2025-11-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 1,
                'room_id' => 1,
                'service_id' => 2,
                'check_in' => '2025-11-02',
                'check_out' => '2025-11-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 1,
                'room_id' => 1,
                'service_id' => 2,
                'check_in' => '2025-11-02',
                'check_out' => '2025-11-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 1,
                'room_id' => 1,
                'service_id' => 2,
                'check_in' => '2025-11-02',
                'check_out' => '2025-11-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 2,
                'room_id' => 2,
                'service_id' => null,
                'check_in' => '2025-12-10',
                'check_out' => '2025-12-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 2,
                'room_id' => 2,
                'service_id' => null,
                'check_in' => '2025-12-10',
                'check_out' => '2025-12-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 2,
                'room_id' => 2,
                'service_id' => null,
                'check_in' => '2025-12-10',
                'check_out' => '2025-12-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 2,
                'room_id' => 2,
                'service_id' => null,
                'check_in' => '2025-12-10',
                'check_out' => '2025-12-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'guest_id' => 2,
                'room_id' => 2,
                'service_id' => null,
                'check_in' => '2025-12-10',
                'check_out' => '2025-12-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
